- type: replace
  path: /releases/-
  value:
    name: "bpm"
    version: "1.1.1"
    url: "https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.1.1"
    sha1: "a7ea57aaf44a8217bae2a3df72a1afc51334e930"

- type: replace
  path: /instance_groups/name=dummy/jobs/-
  value:
    name: bpm
    release: bpm

